SELECT
    search_context_key,
    MIN(event_datetime) AS event_datetime,
    MIN(event_date) AS event_date,
    MIN(event_month) AS event_month,
    MIN(event_week) AS event_week,
    ANY_VALUE(event_iso_day_of_week) AS event_iso_day_of_week,
    ANY_VALUE(event_hour) AS event_hour,
    ANY_VALUE(site_name) AS site_name,
    ANY_VALUE(posa_continent) AS posa_continent,
    ANY_VALUE(user_location_country) AS user_location_country,
    ANY_VALUE(user_location_region) AS user_location_region,
    ANY_VALUE(user_location_city) AS user_location_city,
    ANY_VALUE(user_id) AS user_id,
    ANY_VALUE(device_segment) AS device_segment,
    ANY_VALUE(package_segment) AS package_segment,
    ANY_VALUE(channel) AS channel,
    ANY_VALUE(checkin_date) AS checkin_date,
    ANY_VALUE(checkout_date) AS checkout_date,
    ANY_VALUE(lead_time_days) AS lead_time_days,
    ANY_VALUE(lead_time_segment) AS lead_time_segment,
    ANY_VALUE(stay_nights) AS stay_nights,
    ANY_VALUE(stay_segment) AS stay_segment,
    ANY_VALUE(srch_adults_cnt) AS srch_adults_cnt,
    ANY_VALUE(srch_children_cnt) AS srch_children_cnt,
    ANY_VALUE(srch_rm_cnt) AS srch_rm_cnt,
    ANY_VALUE(party_size) AS party_size,
    ANY_VALUE(traveller_segment) AS traveller_segment,
    ANY_VALUE(srch_destination_id) AS srch_destination_id,
    ANY_VALUE(srch_destination_type_id) AS srch_destination_type_id,
    MODE(hotel_continent) AS primary_hotel_continent,
    MODE(hotel_country) AS primary_hotel_country,
    MODE(hotel_market) AS primary_hotel_market,
    ANY_VALUE(distance_segment) AS distance_segment,
    BOOL_OR(has_valid_stay_dates) AS has_valid_stay_dates,
    BOOL_OR(has_valid_lead_time) AS has_valid_lead_time,
    COUNT(*)::BIGINT AS interaction_rows,
    SUM(event_weight)::BIGINT AS weighted_interactions,
    COUNT(*) FILTER (WHERE is_booking = 0)::BIGINT AS click_rows,
    COALESCE(SUM(event_weight) FILTER (WHERE is_booking = 0), 0)::BIGINT AS weighted_clicks,
    COUNT(*) FILTER (WHERE is_booking = 1)::BIGINT AS booking_rows,
    COALESCE(SUM(event_weight) FILTER (WHERE is_booking = 1), 0)::BIGINT AS weighted_bookings,
    BOOL_OR(is_booking = 1) AS has_booking,
    COUNT(DISTINCT hotel_cluster)::SMALLINT AS distinct_hotel_clusters,
    COUNT(DISTINCT hotel_market)::SMALLINT AS distinct_hotel_markets,
    MODE(hotel_cluster) FILTER (WHERE is_booking = 1) AS booked_hotel_cluster
FROM analytics.fct_hotel_interactions
GROUP BY search_context_key
